### ISSUE TITLE
Git Config is manipulated outside of `auto shipit`

### ISSUE THREAD

**Issue by orta** [intuit/auto-release#124]
**Describe the bug**

If you run `yarn auto xxx` - then your local git config is manipulated. It should probably only happen in `yarn auto shipit` and its substeps when deploying

**To Reproduce**

See the commits in #123, https://github.com/omakase-js/omakase/commit/ccddab848c2a59a9c0f2b8070c1f69498c342dbf and https://github.com/artsy/reaction/pull/1779

**Expected behavior**

Not editing local setup

**Comment by adierkens** [comment]
Comes from https://github.com/intuit/auto-release/blob/master/src/main.ts#L95
