### ISSUE TITLE
What is the difference between this project and standard-release semantic-release?

### ISSUE THREAD

**Issue by jianglin-wu** [intuit/auto-release#153]
[standard-version](https://github.com/conventional-changelog/standard-version)

[semantic-release](https://github.com/semantic-release/semantic-release)

**Is it a repetitive wheel?**

**Comment by hipstersmoothie** [comment]
> https://github.com/semantic-release/semantic-release 

Forces you to use conventional commits which can really restrict outside contribution. And personally I hate having to grapple with formatted commit messages.

Automating your releases via PR labels enables you to run your project in a super easy way,

> https://github.com/conventional-changelog/standard-version

Same problem.

read more here https://artsy.github.io/blog/2019/01/03/label-based-prs/
