### ISSUE TITLE
v2 failing due to unconfigured git user

### ISSUE THREAD

**Issue by zephraph** [intuit/auto-release#155]
**Describe the bug**

When running `auto shipit` v2 is failing unless you explicitly set the git user and password. 

Here's a passing build with v1:
https://circleci.com/gh/artsy/renovate-config/727?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

and a failing build with v2 right after updating:
https://circleci.com/gh/artsy/renovate-config/737?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**To Reproduce**

Updating to v2, ???

**Expected behavior**

Successful deploy without config change

**Additional context**

Having worked with process spawning, I suspect this is likely due to the git process not retaining its envs and context. I'm pretty sure [this line](https://github.com/intuit/auto-release/blob/56f53e649f95d60d0833dd47a988a42fcae9b0b6/src/utils/exec-promise.ts#L12) is the culprit. PR inbound.

**Comment by hipstersmoothie** [comment]
The releases are also failing on the git $branch. I was gonna make a PR but gonna wait for yours!

**Comment by hipstersmoothie** [comment]
I think your PR will fix #156 as well
