### ISSUE TITLE
Still issues where commands fail but CI is reported as passing

### ISSUE THREAD

**Issue by zephraph** [intuit/auto-release#170]
**Describe the bug**

There are still many instances where commands fail but CI doesn't exit. 

`auto pr-check` when some github response gives an error

https://circleci.com/gh/artsy/renovate-config/830?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

`auto shipit` when an npm package fails to be published

https://circleci.com/gh/artsy/reaction/22172?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Expected behavior**

CI Task fails appropriately

**Comment by hipstersmoothie** [comment]
I tested my changes with you two cases and it worked!
