### ISSUE TITLE
Some error messages getting dropped by promise-exec

### ISSUE THREAD

**Issue by zephraph** [intuit/auto-release#183]
**Describe the bug**

When `promise-exec` detects there's an error exit code it only logs `stderr`. See that [here](https://github.com/intuit/auto-release/blob/d21838d3f2926b5b9525808c8a053aa16ae9c981/src/utils/exec-promise.ts#L49). That assumes that all cli tools are good citizens and don't push errors to stdout... which is certainly not the case, heh.

**To Reproduce**

Have auto-release call a command that exits with 1 but dumps its error output to stdout. 

**Expected behavior**

stdout and stderr should both be logged (if they're non-empty)

**Comment by hipstersmoothie** [comment]
actually just ran into this! putting a tiny PR together now
