### ISSUE TITLE
Shared configuration

### ISSUE THREAD

**Issue by zephraph** [intuit/auto-release#191]
**Is your feature request related to a problem? Please describe.**

In an org with many repos it can be a bit painful to update `.autorc`'s. It would be nice to be able to have an extension method like [eslint](https://eslint.org/docs/developer-guide/shareable-configs) or [renovatebot](https://renovatebot.com/docs/config-presets/) to be able to have a centralized shared config that can be overridden on a per project basis (if need be). 

**Describe the solution you'd like**

Create some mechanism for having shared configuration. It could be as complex as a node_module or as simple as a URL to a file.

**Comment by hipstersmoothie** [comment]
So something like 

```json
{
   "extends": "artsy"
}
```

Where `artsy` could be `auto-config-artsy`?

**Comment by hipstersmoothie** [comment]
Once #184 is merged we will be able to have these config files type checked easily too
