### ISSUE TITLE
--dry-run for sanity checks

### ISSUE THREAD

**Issue by aleclarson** [intuit/auto-release#220]
I would love a `--dry-run` (and `-n` for short) to verify everything will work as expected. Just like `npm` has for its `publish` command.

**Comment by hipstersmoothie** [comment]
There is dry run on a few of the commands. What commands do you need it on?

**Comment by hipstersmoothie** [comment]
`auto version` doesn't actually change any files so it doesn't have a --dry flag

`changelog`, `pr-check`, and `release` have the flag currently.

I'll look into adding it for `shipit` but i feel like there was a reason I couldn't add it.

**Comment by aleclarson** [comment]
> `auto version` doesn't actually change any files so it doesn't have a --dry flag

Yes I'm aware of that. I was just suggesting that maybe you intended `auto version` to be the dry-run version of `auto shipit`, but now I know that's not the case.

**Comment by hipstersmoothie** [comment]
Before the `shipit` command `auto` was a collection of CLI tools the user could string together for the various parts of the release. All shipit does is

- run `auto version`
- run `auto changelog`
- call publish hook to defer to plugin 
- run `auto release`

**Comment by hipstersmoothie** [comment]
This use to be the required setup before `shipit` https://intuit.github.io/auto-release/pages/getting-started.html#detailed-setup
