### ISSUE TITLE
Local ".env" file for credentials

### ISSUE THREAD

**Issue by aleclarson** [intuit/auto-release#221]
I'm not a fan of either (1) providing `GH_TOKEN` every time I use the CLI locally, or (2) exporting `GH_TOKEN` from `~/.zshrc` or similar.

Maybe we could check for a `.env` file relative to the `package.json` file, which could look like:
```
GH_TOKEN=4exxx498bxxxd3a5513fxx5099x41f75xxxxb61
```

Then the user would add `.env` to `.gitignore` for security.

**Comment by hipstersmoothie** [comment]
https://github.com/motdotla/dotenv
