### ISSUE TITLE
Better type def for CLI args

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto-release#75]
Right now it basically has all type as possible available. It would be awesome if we could define an interface for each command and get rid of some `!`s

NOTE: I've spent hours trying to get this to work just right but haven't really gotten close at all

**Comment by orta** [comment]
Depending on how bold you want to be about this, [oclif](https://oclif.io) is the best CLI framework I've seen for this kinda thing (and is fully typed)
