### ISSUE TITLE
auto release badge

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto-release#8]

**Comment by adierkens** [comment]
[![Auto Release](https://img.shields.io/badge/release-auto.svg?colorA=gray&colorB=red&label=auto&style=for-the-badge&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsTAAALEwEAmpwYAAABWWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS40LjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgpMwidZAAACoklEQVQoFW1SXUhTcRQ/d9dyTYfmx1ZTyWnZwLVsLcRic4pt0lMkXqqXhIzwwaIQoXwZUWoP5YPNj3xafiQbgSHz4sdifjFqjaTQqCazuWUNiS1r083df///MJ86cO4593d+5+N/OBRgMUMtzYAlTvx1E+Tw06CcEpyXAcQ3ufDociwKjgwGvCSOAHgUAJdIIsATEGa2grwhbG8YRZuTCP1kEVp/iVCYRX9e1Y+8Abj2DiCdcM0ANE5OSMqLqwZbtiS3lObmuk5fKvodXltwUzx+ctL+Q0fWxj4KDuTX1HsmrfPvTQOVDEA0kTWov2n69HwCjd/r/nwFoHCn2K7B3Uq8RqMvNjyMFgB6E4EmAMVUWx+aau+L3gE4s8vecVYf39pH3LcApSsdHdxySwtyAsh5JbobTLHyOGysBAbbAOaPFRaxmSLRhPhgzl1BuuRE3u2OyFhjY7IK4PXW6qq5oKoKBOXlF3hJyXuzXOx0HPl/jZDKkozspngsWvZjzf8gHPyGpwTJuc7OLRJL8/kGfTMz23uyM7NAXaBoxZgbazdCiEcIGo1Gyufzv2B3TiwWpxAMx8gi2xUArhqF/D75eVh7+WJzEsYDgUCxzWZbIkStVsvHZttut3PYciqFQl5WUfHB7fcDy7L4VXhjPT09cavVioRCIUuA/4ler5+anZ1FXUYjOZQSGn++B4PBXKVSeRIHD4tEIo3L5SJjhrCSrqeqq6sH6urqtBRFwbP+fpPb7e79dwC0Wq2eYBimUiqVgsPhgNTU1K80TfNCoVCeSqUCkjQ0NDRtNpvP4mIxkki6kvbEf2QwGK5zHCfQ6XQQiUTA4/EAnmjDYrE8dTqdzZhD3rx7cmSbBCCSj7VKJpMdxd05r9e7tLi4aMOYDyuRBPcvABMIwNAJzxIAAAAASUVORK5CYII=)](https://github.com/intuit/auto-release)

**Comment by hipstersmoothie** [comment]
@adierkens i can give you a good png for that

![favicon](https://user-images.githubusercontent.com/1192452/50034335-2f244300-ffb1-11e8-88a5-b0e891daf280.png)

**Comment by hipstersmoothie** [comment]
32px;

![Uploading PATCH_MINOR_MAJOR32A.png…]()

**Comment by hipstersmoothie** [comment]
https://img.shields.io/badge/release-auto.svg?colorA=gray&colorB=9B065A&label=auto&style=for-the-badge&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACXElEQVR4AY3BXWiVZQAA4Of9vu+cbbr+/GEWRVnsxrDQbpTWii6CNrAfW7KKiOoquuiiKyOCyq7KmzKQGRLJrnJemKOL6BfWLpyROCpbDZ0bI51z4s7+zvnezjqDk1TQ84SewlOWlZcyRF0f97es3TT1Qmly1TbBdgQMZusMLow6OPpcPh4XSZr8JbMiTSsuV5pfnjje8vDabVMdcSIIabQsVnSm1+ssDcV7ywv6C43etyLdkW62LCQ+yivpaxeG16y+o+3ML6vXzV+pLKaf42R2reLShLPjb8SN+ZxdSYNW9KnK1OzOY3y+OSspz94+GwfufDZ5Z/Cnpp8bSXBNdG5P3jp30ZHGJjeLnsYoXk93pJtvwWdBsCpp+G04H2vtnzl94YuhGUf7c8Oncnfdk1h/Nrl47ut4sFCwU7AO7TiU4RVVN4Xr8iOVH3cdMPCQYSXDjlOeV/XBV0v231bUVkzmRsSOjN/VvJoVZU/mcs0aBtaH5iHRi+jBZQzhu7GRuKdjZGHx1+ZGW0IyeiaPX87H+GDKY+nO9O6uBoWpKbPvnXdl+EQ+dmJJZRxd2Ij7cQnfj+fRjUkQmb4hhE0Vzme7y0f/KEgL00qPT8fSsUSYxQEUsU/NaVV95Yq+cqW4IYTulhAm5sXFbCxO34c1aj7JxWNqPsQplDGgrm0yxu7JGFXNJOhV96arfYsBV3tb3acJ9qrbih7/bR+2q3s3xSVkaFezFY8gImIDOrEfj6rbi96grhfd/p/DeEJVqu4wKmhH4t/leAsvWRH80614Bg9gCwJ+wDc4hFF/8ydm0+g9BmLv3gAAAABJRU5ErkJggg==

**Comment by hipstersmoothie** [comment]
going with 20x20
